### ISSUE TITLE
please add volume control

### ISSUE THREAD

**Issue by ericslaw** [skiptomyliu/milkshake#22]
The app exposes no volume control.
It seems to be at least twice the volume of any other sound source on my machine.
An app-specific setting for output volume would be very helpful.

**Comment by skiptomyliu** [comment]
@ericslaw @jrspirent - Thanks for the feedback and sorry for the late response.  I had no idea people were checking in here until now!    I'll work on getting this in.

**Comment by skiptomyliu** [comment]
@ericslaw @jrspirent , I've added volume control, you can directly [download the `1.0.5` dmg](https://github.com/skiptomyliu/milkshake/raw/master/App/Milkshake.dmg), or wait get the updated version from the store once it's approved by Apple.

**Comment by skiptomyliu** [comment]
This has now been released on the app store.
