### ISSUE TITLE
Crashed twice during playing

### ISSUE THREAD

**Issue by radfaraf** [skiptomyliu/milkshake#29]
Milkshake version:  1.0.6
OS Version:            Mac OS X 10.14.3 
I had it crash twice when playing. Not sure what the software was doing 100% as I was occupied with other things and not focusing that much on the music. It seemed like both times it was either very close to switching songs due to being near the end of ones, or in the process of switching. I've played many songs too without issue, so I can't repeat it at will each time. Player was in the now playing view each time.

Crash logs are attached. Let me know if any other info might be helpful in figuring out what causes this.

[Milkshake crash.zip](https://github.com/skiptomyliu/milkshake/files/2902862/Milkshake.crash.zip)

**Comment by skiptomyliu** [comment]
Thanks for the report @radfaraf and the usage, do you recall what station you were listening to?  

Also, free version / premium?

**Comment by radfaraf** [comment]
Free version. I have a custom channel I made myself with chill ambient eletronic music. I've had some more crashes since then, they all seem randomly during playback. I had one even that was after the player was paused, I clicked play and it started again, but only to crash within 10 seconds. All the others seem random as far as where they were in the song.

**Comment by skiptomyliu** [comment]
thanks for the additional info @radfaraf.  Definitely eager to chase this down.

Do you have an electronic artist that is part of this channel?  I'll create a station seeded off this hoping to make it crash.

Also hate to ask you this, but do you have the crash file in non zip format?  I'm a little paranoid with downloading random zip files. 😄

**Comment by radfaraf** [comment]
I see we can share our channels which would allow you to play mine exactly instead of a imitation version. Maybe then your can subscribe to and that will make it shown in the player for you too hopefully? Here is a link to it: https://www.pandora.com/station/play/42065292027619810

Here I uploaded all the files without zipping them to this site (github doesn't allow me to upload random extensions, so that is why I zipped them):
https://filebin.net/6otfymkz5tzotl6m

**Comment by skiptomyliu** [comment]
Ha sweet idea on the share.  I've currently started the station and I'll let it run for a bit to try to reproduce.  I'll also peruse the crash logs a bit after work today.  Really appreciate it.

**Comment by skiptomyliu** [comment]
I haven't forgotten about this.   This is taking me a bit to track down.  Looks like it only happens on Mojave.

**Comment by radfaraf** [comment]
Thanks for the update.

**Comment by skiptomyliu** [comment]
@radfaraf , out of curiosity was it crashing after a long pause?  The following update will fix this issue:

https://github.com/skiptomyliu/milkshake/blob/2019-2-1-icon/App/Milkshake.dmg

**Comment by radfaraf** [comment]
Sometimes, it would and other times it was fine, getting that one to see if it makes a difference.

**Comment by radfaraf** [comment]
That file is downloading as only 72kb and won't open the archive.

**Comment by skiptomyliu** [comment]
huh, weird, it should be 5.1MB.  Sorry, maybe some confusion, that link above I originally posted requires you to click download on the page.   Here's the raw link:

https://github.com/skiptomyliu/milkshake/raw/2019-2-1-icon/App/Milkshake.dmg

**Comment by skiptomyliu** [comment]
@radfaraf , I just sent an update to the Apple App Store as well.  You should receive an update notice within the next 24 hours.

**Comment by radfaraf** [comment]
I am using the second link you provided. So far it seems to have fixed all the crashes. None since the update, both by playing it for several hours yesterday and today. Plus tried a few long pauses and resume playback afterwards.

**Comment by skiptomyliu** [comment]
That's great to hear it's working out.  Took a while to find the issue.  Again thanks for bearing with me.  The latest update is also on the appstore now too (in case you want to re-download so you get the latest updates automatically from Apple).

**Comment by radfaraf** [comment]
Closing this, had a lot more time to test it and zero crashes still!
