### ISSUE TITLE
Ctrl+Cmd+Space shortcut overrides OSX emoji dropdown

### ISSUE THREAD

**Issue by aaronrenner** [skiptomyliu/milkshake#31]
When logged in to Milkshake, if I press `Ctrl+Cmd+Space` to insert an emoji in to a text field of another application, the Milkshake window pops up instead of the OSX insert emoji dropdown. This only happens when Milkshake is logged in to Pandora, not if you first open it and leave it at the the login screen.

Thanks so much for this awesome app! I really appreciate having a good desktop pandora client.

**Comment by aaronrenner** [comment]
Awesome. Thank you! 💛 💙 💚

**Comment by skiptomyliu** [comment]
Just giving you a quick heads up that it's currently pending review by Apple.  Release should be out sometime in next day or two.  Took a little bit since I also caught another crash bug, so I bundled in that fix as well.

**Comment by skiptomyliu** [comment]
@aaronrenner , just giving you a heads up that this has been fixed and is now available as an update on the appstore.

**Comment by aaronrenner** [comment]
Thank you so much! I just tried it out and it works great! ❤️
