### ISSUE TITLE
Create preference to disable equalizer.

### ISSUE THREAD

**Issue by rangerdth** [skiptomyliu/milkshake#34]
It would be nice to be able to enable/disable the equalizer on the bottom.

**Comment by skiptomyliu** [comment]
@rangerdth , you can disable the equalizer by going from Music > Disable Spectrum

However the setting doesn't persist across restarts which I can work on getting in.

**Comment by rangerdth** [comment]
Ah, I see that now, I was looking for "Equalizer", as I saw the comment in your code. Thanks.
