### ISSUE TITLE
Enable Shuffle

### ISSUE THREAD

**Issue by christopherpickering** [skiptomyliu/milkshake#38]
Hi, Can you create an option to allow station shuffle?
Thanks for the app!

**Comment by fontaholic** [comment]
how do you actually use the shuffle? i have enable shuffle selected in my app, but can only get stations to play...

**Comment by skiptomyliu** [comment]
really late reply here!   The shuffle was only intended for pandora premium, which would shuffle playlists.  I'm planning to make that more clear in the UI.

**Comment by skiptomyliu** [comment]
Closing this out.  https://github.com/skiptomyliu/milkshake/pull/49 will only show shuffle if users are on premium.

**Comment by skiptomyliu** [comment]
Sorry, follow up.  Released ability to shuffle stations https://github.com/skiptomyliu/milkshake/issues/53
