### ISSUE TITLE
Milkshake Stopped Working

### ISSUE THREAD

**Issue by jrotenberg02116** [skiptomyliu/milkshake#43]
I use Mac OS Catalina.  A few days ago, Milkshake stopped working.  When I try to log into my Pandora account, it says "Invalid user name/password."  But the password works fine on the Pandora website.

<img width="296" alt="Screen Shot 2021-02-14 at 8 09 26 AM" src="https://user-images.githubusercontent.com/79047049/107877692-f8515c80-6e9b-11eb-9566-e4a107e851d8.png">

**Comment by christopherpickering** [comment]
Same problem :( 
![gif](https://media0.giphy.com/media/l1KVaj5UcbHwrBMqI/200w.webp?cid=ecf05e47d9qrre7i04p3otkqb1a9iqjwvkwkgg078h3g3enj&rid=200w.webp)

**Comment by christopherpickering** [comment]
https://github.com/skiptomyliu/milkshake/issues/42#issuecomment-778193767

**Comment by JeffScanco** [comment]
I also have the same issue.  I thought it was because I upgraded to Big Sur recently, but I hadn't opened Milkshake in a while.  Did Pandora do something at their end to block logins from non-browser apps (other than their own)?

**Comment by skiptomyliu** [comment]
Closing this duplicate report in favor of https://github.com/skiptomyliu/milkshake/issues/42 , i'm finding some time to fix the issue.
