### ISSUE TITLE
Not accepting my log in information

### ISSUE THREAD

**Issue by thsutton907** [skiptomyliu/milkshake#44]
I downloaded the milkshake app and used my pandora log in information but I get the message "Invalid username and/or password". I am able to sign directly into pandora just fine. I have tried signing into milkshake app several times already to make sure I am not using typos. Is there something I am missing?

**Comment by djames42** [comment]
Take a look at the previous issues, particularly [Issue #42](https://github.com/skiptomyliu/milkshake/issues/42)

**Comment by skiptomyliu** [comment]
Closing in favor of https://github.com/skiptomyliu/milkshake/issues/42 , i'm finding some time to fix the issue.
