### ISSUE TITLE
Shuffling stations

### ISSUE THREAD

**Issue by giantspeck** [skiptomyliu/milkshake#53]
Would it be possible to add a feature to shuffle stations?  As far as I can tell, there is a shuffle feature, but it's only for playlists.

**Comment by skiptomyliu** [comment]
Will aim to add on next release.  Working on the feature in this PR: https://github.com/skiptomyliu/milkshake/pull/54

**Comment by skiptomyliu** [comment]
@giantspeck , released in v1.3.0.  It's available for download here https://github.com/skiptomyliu/milkshake/releases/tag/v1.3.0

And will be available for download from the macOS store in a few days.

**Comment by giantspeck** [comment]
Thank you for your hard work!  It's so nice to have a standalone Pandora app on macOS again!
